// <auto-generated />
using System;
using EFP.API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EFP.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EfpDbContext))]
    [Migration("20260906030912_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFP.API.Infrastructure.Persistence.FileJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("AcceptedRows")
                        .HasColumnType("bigint");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CancelRequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentRow")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorCode")
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<long?>("InputBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("InputObjectKey")
                        .HasColumnType("text");

                    b.Property<short>("JobType")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text");

                    b.Property<int>("MaxAttempt")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("OutputBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OutputObjectKey")
                        .HasColumnType("text");

                    b.Property<short>("Phase")
                        .HasColumnType("smallint");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<long>("ProcessedRows")
                        .HasColumnType("bigint");

                    b.Property<long>("RejectedRows")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalRows")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("UploadId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LeaseExpiresAt");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.HasIndex("TenantId", "Status");

                    b.HasIndex("Status", "Priority", "CreatedAt");

                    b.ToTable("file_jobs", (string)null);
                });

            modelBuilder.Entity("EFP.API.Infrastructure.Persistence.FileJobProgressEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AcceptedRows")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesRead")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesWritten")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CurrentRow")
                        .HasColumnType("bigint");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<short>("Phase")
                        .HasColumnType("smallint");

                    b.Property<long>("ProcessedRows")
                        .HasColumnType("bigint");

                    b.Property<long>("RejectedRows")
                        .HasColumnType("bigint");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalRows")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Sequence")
                        .IsUnique();

                    b.ToTable("file_job_progress", (string)null);
                });

            modelBuilder.Entity("EFP.API.Infrastructure.Persistence.IdempotencyRecordEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("EFP.API.Infrastructure.Persistence.StorageObjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ContentLength")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<short>("Provider")
                        .HasColumnType("smallint");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TenantId", "ObjectKey")
                        .IsUnique();

                    b.ToTable("storage_objects", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
